import pandas as pd
import statsmodels.stats.multitest as mt
import numpy as np

def import_data(input):

    """
    Reads in file generated by SMR-IVW software (.msmr file)

    Args:
    - input: path to input file

    Returns:
    - results dataframe
    """

    df = pd.read_csv(input, sep = '\t')
    return df

def filter(df):
    """
    Filters results by number of IVs and hypothesis corrects p-values (2 methods available)

    Args:
    - df: dataframe of results

    Returns:
    - filtered dataframe of results
    """
    df = df.sort_values(by=['ProbeChr', 'Probe_bp'], ascending=True)
    #df = df.sort_values(by='b_ivw', ascending=False) #sorts by ivw effect size
    df = df.loc[df['n_iv'] >= 3] #filter by number of IVs, here set to 3
    
    #Bonferonni multiple hypothesis correction
    #n_hits = df.shape[0] - 1
    #df = df.loc[(df['p_ivw'] <= 0.05/n_hits)] 

    #FDR multiple hypothesis correction, BH method
    reject, q_values, _, _ = mt.multipletests(df['p_ivw'], method='fdr_bh')
    df['keep'] = reject
    df = df.loc[(df['keep'] == 1)]

    return df

def main():
    input = '/Users/mqtl_ivw_warfarin_new_1000G.msmr' #.msmr file path here

    frame = import_data(input)

    filtered = filter(frame)
    
    print (filtered)

    filtered.to_csv("/Users/warfarin_step1_ev.csv", sep = '\t') #name for output file

if __name__ == "__main__":
    main()